"""Complex-domain fields for the uncertainty-focused Paper A experiments.

The benchmark is intentionally not a rectangular image with pixels removed.  A
wall separates two nearby rooms and leaves only a narrow passage, so Euclidean
distance and diffusion/geodesic distance disagree.  The target is generated by
a diffusion--oscillation system on the resulting graph, with an off-prior
localized transient to avoid making the experiment tautological.
"""

from __future__ import annotations

from dataclasses import dataclass
import math

import numpy as np
import torch
from scipy import sparse
from scipy.sparse.linalg import eigsh

from .bases import BasisSpec, evaluate_basis


@dataclass
class ComplexGeometryField:
    name: str
    values: torch.Tensor                 # [time, node]
    coordinates: torch.Tensor            # [time * node, 3] = (t, x, y)
    indices: torch.Tensor                # [time * node, 2] = (time, node)
    spatial_coordinates: torch.Tensor    # [node, 2]
    graph_basis: torch.Tensor             # [node, modes], RMS-normalized
    graph_eigenvalues: torch.Tensor       # normalized by first nonzero eigenvalue
    adjacency: sparse.csr_matrix
    domain_mask: torch.Tensor             # [ny, nx]
    description: str

    @property
    def shape(self) -> tuple[int, int]:
        return tuple(self.values.shape)

    @property
    def flat_values(self) -> torch.Tensor:
        return self.values.reshape(-1)


def _two_room_mask(nx: int, ny: int) -> np.ndarray:
    """Two rooms with a one-cell bent passage and an internal obstacle."""
    mask = np.ones((ny, nx), dtype=bool)
    wall_x = nx // 2
    mask[:, wall_x] = False
    # A narrow lower passage makes opposite sides close in Euclidean distance
    # but far in graph/diffusion distance.
    door = slice(max(1, ny // 6 - 1), min(ny - 1, ny // 6 + 2))
    mask[door, wall_x] = True
    # Non-convex obstacle in the right room.
    y0, y1 = ny // 2, min(ny - 2, ny // 2 + ny // 5)
    x0, x1 = wall_x + nx // 7, min(nx - 2, wall_x + nx // 4)
    mask[y0:y1, x0:x1] = False
    return mask


def _grid_graph(mask: np.ndarray) -> tuple[np.ndarray, sparse.csr_matrix]:
    ys, xs = np.where(mask)
    points = np.stack([xs, ys], axis=1)
    lookup = {tuple(p): i for i, p in enumerate(points)}
    rows, cols = [], []
    for i, (x, y) in enumerate(points):
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            j = lookup.get((x + dx, y + dy))
            if j is not None:
                rows.append(i); cols.append(j)
    data = np.ones(len(rows), dtype=np.float64)
    a = sparse.csr_matrix((data, (rows, cols)), shape=(len(points), len(points)))
    return points, a.maximum(a.T)


def make_two_room_diffusion(
    *, nx: int = 38, ny: int = 28, n_time: int = 24,
    n_graph_modes: int = 96, seed: int = 31415, variant: str = "spectral",
) -> ComplexGeometryField:
    mask = _two_room_mask(nx, ny)
    points, adjacency = _grid_graph(mask)
    degree = np.asarray(adjacency.sum(1)).ravel()
    lap = sparse.diags(degree) - adjacency
    k = min(n_graph_modes, len(points) - 2)
    eigval, eigvec = eigsh(lap, k=k, which="SM", tol=1e-7)
    order = np.argsort(eigval)
    eigval, eigvec = eigval[order], eigvec[:, order]
    # Deterministic signs make generated fields stable across scipy versions.
    for j in range(eigvec.shape[1]):
        anchor = np.argmax(np.abs(eigvec[:, j]))
        if eigvec[anchor, j] < 0:
            eigvec[:, j] *= -1
    eigvec /= np.sqrt(np.mean(eigvec ** 2, axis=0, keepdims=True))
    scale = eigval[np.flatnonzero(eigval > 1e-8)[0]]
    eigval = eigval / scale

    xy = points.astype(np.float64)
    xy[:, 0] /= max(nx - 1, 1); xy[:, 1] /= max(ny - 1, 1)
    t = np.linspace(0.0, 1.0, n_time)
    rng = np.random.default_rng(seed)

    if variant == "spectral":
        # A controlled graph-PDE field: low graph modes receive oscillatory
        # forcing.  The transient below still introduces mild prior mismatch.
        n_signal = min(18, eigvec.shape[1])
        coeff = rng.normal(size=n_signal) * (1.0 + eigval[:n_signal]) ** -0.9
        phase = rng.uniform(0, 2 * np.pi, size=n_signal)
        freq = rng.integers(0, 5, size=n_signal)
        temporal = np.cos(2 * np.pi * t[:, None] * freq + phase)
        temporal *= np.exp(-0.10 * t[:, None] * eigval[:n_signal])
        field = (temporal * coeff[None, :]) @ eigvec[:, :n_signal].T
        d2 = ((xy[:, 0] - 0.80) / 0.10) ** 2 + ((xy[:, 1] - 0.76) / 0.13) ** 2
        pulse = np.exp(-0.5 * d2)[None, :] * np.exp(-((t[:, None] - 0.62) / 0.13) ** 2)
        field += 0.28 * pulse
        field += 0.07 * np.tanh(field) * np.roll(field, 1, axis=0)
    elif variant == "heterogeneous":
        # Strongly misspecified task: nonlinear dynamics use a *different*,
        # heterogeneous operator, chirped forcing, and moving local sources.
        coo = adjacency.tocoo()
        midpoint_x = .5 * (xy[coo.row, 0] + xy[coo.col, 0])
        midpoint_y = .5 * (xy[coo.row, 1] + xy[coo.col, 1])
        weights = .35 + 1.25 * (1 + np.sin(5.3 * midpoint_x + 3.1 * midpoint_y)) / 2
        ah = sparse.csr_matrix((weights, (coo.row, coo.col)), adjacency.shape).maximum(
            sparse.csr_matrix((weights, (coo.col, coo.row)), adjacency.shape))
        lh = sparse.diags(np.asarray(ah.sum(1)).ravel()) - ah
        lh = lh / max(float(np.asarray(ah.sum(1)).max()), 1.)
        # The heterogeneous conductivity is treated as known operator metadata,
        # analogous to a PDE coefficient or mesh material map.  Crucially, the
        # nonlinear reaction, chirp, moving source and shock below are not
        # samples from the resulting Gaussian prior.
        heigval, heigvec = eigsh(lh, k=k, which="SM", tol=1e-7)
        horder = np.argsort(heigval); heigval, heigvec = heigval[horder], heigvec[:, horder]
        for q in range(heigvec.shape[1]):
            anchor = np.argmax(np.abs(heigvec[:, q]))
            if heigvec[anchor, q] < 0: heigvec[:, q] *= -1
        heigvec /= np.sqrt(np.mean(heigvec ** 2, axis=0, keepdims=True))
        hscale = heigval[np.flatnonzero(heigval > 1e-8)[0]]
        eigvec, eigval = heigvec, heigval / hscale
        left = np.exp(-.5 * (((xy[:, 0] - .18) / .10) ** 2 + ((xy[:, 1] - .78) / .12) ** 2))
        right = np.exp(-.5 * (((xy[:, 0] - .82) / .09) ** 2 + ((xy[:, 1] - .28) / .10) ** 2))
        u = 1.4 * left - .9 * right
        frames = []
        for j, tj in enumerate(t):
            frames.append(u.copy())
            cx = .62 + .20 * np.sin(2 * np.pi * (tj + .22 * tj * tj))
            cy = .66 - .27 * tj
            moving = np.exp(-.5 * (((xy[:, 0] - cx) / .07) ** 2 + ((xy[:, 1] - cy) / .09) ** 2))
            chirp = np.sin(2 * np.pi * (1.1 * tj + 2.7 * tj * tj) + .4)
            # reaction--diffusion with heterogeneous conductivity
            u = u - .24 * (lh @ u) + .035 * (u - .35 * u ** 3) + .18 * chirp * moving
        field = np.stack(frames)
        # A sharp intervention late in time is deliberately outside the
        # stationary separable prior family.
        shock = np.exp(-.5 * (((xy[:, 0] - .74) / .055) ** 2 + ((xy[:, 1] - .82) / .07) ** 2))
        field += .45 * np.exp(-((t[:, None] - .78) / .06) ** 2) * shock[None, :]
    else:
        raise ValueError(f"unknown variant: {variant}")
    field = (field - field.mean()) / field.std()

    tt = np.repeat(t, len(points))
    coords = np.column_stack([tt, np.tile(xy[:, 0], n_time), np.tile(xy[:, 1], n_time)])
    indices = np.column_stack([
        np.repeat(np.arange(n_time), len(points)),
        np.tile(np.arange(len(points)), n_time),
    ])
    return ComplexGeometryField(
        name=f"two_room_{variant}",
        values=torch.from_numpy(field.astype(np.float32)),
        coordinates=torch.from_numpy(coords.astype(np.float32)),
        indices=torch.from_numpy(indices.astype(np.int64)),
        spatial_coordinates=torch.from_numpy(xy.astype(np.float32)),
        graph_basis=torch.from_numpy(eigvec.astype(np.float32)),
        graph_eigenvalues=torch.from_numpy(eigval.astype(np.float32)),
        adjacency=adjacency,
        domain_mask=torch.from_numpy(mask),
        description=("Field on two rooms separated by a wall with a narrow passage; variant="
                     f"{variant}. The heterogeneous variant uses a mismatched operator, nonlinear "
                     "dynamics, chirped forcing, and a localized intervention."),
    )


def graph_time_features(data: ComplexGeometryField, max_features: int = 256,
                        time_frequencies: int = 7) -> tuple[torch.Tensor, torch.Tensor]:
    """Joint low-energy eigenfeatures of graph Laplacian + time Laplacian."""
    # The field contains oscillatory forcing; the temporal circle basis captures
    # phase without forcing every component to be even at t=0.  Decay and the
    # transient deliberately violate exact temporal periodicity slightly.
    spec = BasisSpec("periodic", time_frequencies, "time-oscillation")
    phi_t, eig_t = evaluate_basis(data.coordinates[:, 0], spec)
    node = data.indices[:, 1]
    phi_g = data.graph_basis[node]
    eig_g = data.graph_eigenvalues
    combos = torch.cartesian_prod(torch.arange(phi_t.shape[1]), torch.arange(phi_g.shape[1]))
    separate = torch.stack([eig_t[combos[:, 0]], eig_g[combos[:, 1]]], 1)
    joint = separate.sum(1)
    # max_features >= the full tensor product explicitly disables truncation.
    # Otherwise use a low joint-energy prefix for the Round-1 ablation.
    keep = torch.argsort(joint)[:min(max_features, len(joint))]
    combos, separate = combos[keep], separate[keep]
    phi = phi_t[:, combos[:, 0]] * phi_g[:, combos[:, 1]]
    return _rms_normalize(phi), separate


def rectangular_time_features(data: ComplexGeometryField, max_features: int = 256,
                              frequencies: int = 10) -> tuple[torch.Tensor, torch.Tensor]:
    """Wrong-geometry control: separable rectangular Neumann eigenfunctions."""
    specs = [BasisSpec("periodic", 7, "time"), BasisSpec("neumann", frequencies, "x"),
             BasisSpec("neumann", frequencies, "y")]
    basis, eigs = [], []
    for d, spec in enumerate(specs):
        p, e = evaluate_basis(data.coordinates[:, d], spec)
        basis.append(p); eigs.append(e)
    combos = torch.cartesian_prod(*[torch.arange(p.shape[1]) for p in basis])
    joint = sum(eigs[d][combos[:, d]] for d in range(3))
    keep = torch.argsort(joint)[:min(max_features, len(joint))]
    combos, joint = combos[keep], joint[keep]
    phi = torch.ones(len(data.coordinates), len(keep))
    for d in range(3):
        phi *= basis[d][:, combos[:, d]]
    return _rms_normalize(phi), joint


def rff_features(data: ComplexGeometryField, max_features: int = 256,
                 seed: int = 2026, lengthscale: float = 0.25) -> tuple[torch.Tensor, torch.Tensor]:
    """Matched-size stationary Euclidean random Fourier feature control."""
    g = torch.Generator().manual_seed(seed)
    half = max_features // 2
    omega = torch.randn(3, half, generator=g) / lengthscale
    phase = data.coordinates @ omega
    phi = torch.cat([torch.cos(phase), torch.sin(phase)], dim=1)
    eig = torch.cat([omega.square().sum(0), omega.square().sum(0)])
    return _rms_normalize(phi[:, :max_features]), eig[:max_features]


def _rms_normalize(phi: torch.Tensor) -> torch.Tensor:
    return phi / phi.square().mean(0, keepdim=True).sqrt().clamp_min(1e-8)
